<?php
namespace app\index\controller;

use app\common\Caches;
use app\common\StringRsa;
use think\facade\Cache;

class Action extends Basics
{

    protected $uid ;
    /**
     * Action constructor.
     */
    public function initialize(){
        parent::initialize(); // TODO: Change the autogenerated stub
        //判断用户是否已经登录
        if(!empty($_GET['gettoken'])){
            $token = empty( $_GET['gettoken'] )?trim($this->request->param('gettoken')):trim($_GET['gettoken']);
            $tokens = StringRsa::getUserIDFromToken($token);
            if($tokens===null){
                $this->echo_json_exit(10008);
                exit;
            }elseif($tokens==false){
                $this->echo_json_exit(10007);
                exit;
            }else{
                $this->uid = $tokens['id'];
            }
        }elseif(empty($_GET['token']) && empty($this->request->param('token')) ){
            $this->echo_json_exit(30003);
        }else{
            $token = empty( $_GET['token'] )?trim($this->request->param('token')):trim($_GET['token']);
            $tokens = StringRsa::getUserIDFromToken($token);
            if($tokens===null){
                $this->echo_json_exit(10008);
                exit;
            }elseif($tokens==false){
                $this->echo_json_exit(10007);
                exit;
            }else{
                if(!Cache::get($token)){
                    $this->echo_json_exit(10009);
                    exit;
                }
                $this->uid = $tokens['id'];
            }
        }

    }

    /**
     * 验证登录用户的 状态
     */
    public function validate_status()
    {
        $uid = $this->uid;
        $myinfo = Caches::MyuserInfoFiled($uid);
        $viptype = $myinfo['viptype'];
        $myuserStatus=Caches::MyuserXyStatus($uid,$viptype);
        $status=$myuserStatus['status'];
        if($status!=1  &&  $status !=2 ){
            $this->echo_json_exit(22001);
        }
    }
}
