<?php
namespace app\index\controller;

use think\Controller;
use think\Response;

class Basics extends Controller
{
    protected function initialize ()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $origin = isset($_SERVER['HTTP_ORIGIN'])? $_SERVER['HTTP_ORIGIN'] : '';
        $allow_origin = array(
            'https://wapi.wisecareer.org',
	        'http://xy.wisecareer.org',
	        'http://xue.wisecareer.org',
	        'http://tapi.wisecareer.org',
			'http://api.wisecareer.org',
			'http://zt.wisecareer.org',
			'http://fx.wisecareer.org',
        );
        if(in_array($origin, $allow_origin)){
            header("Access-Control-Allow-Credentials: true");
            header('Access-Control-Allow-Origin:'.$origin);
            header('Access-Control-Allow-Headers:x-requested-with,content-type');
            //header("Access-Control-Allow-Headers: Origin, X-Requested-With, Content-Type, Accept");
        }

    }


    protected function message($data,$time=3)
    {
        $msg = $data['msg'];
        $url = $data['url'];
        $str = '<!DOCTYPE html><html lang="en"><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1,user-scalable=0" />
                <meta name="MobileOptimized" content="320"/>' ;
        $str .= '<link rel="stylesheet" href="'.config('template.tpl_replace_string.__LIB__').'/layer/mobile/need/layer.css"/>';
        $str .= '<script src="'.config('template.tpl_replace_string.__PUBLIC__').'/js/jquery-1.8.3.min.js"></script>';
        $str .=' <script src="'.config('template.tpl_replace_string.__LIB__').'/layer/mobile/layer.js"></script></head>' ;
        if($data['type'] == 1){
            $str.="<body><script> layer.open({
                        content: '".$msg."！'
                        ,skin: 'msg'
                        ,time: ".$time." //2秒后自动关闭
                        
                  },function(){
                              window.location.href='".$url."'
                        });</script></script></body>";
        }elseif($data['type'] ==2){

            $str .= "<body><script>	layer.open({
					content: '".$msg."！'
					,shadeClose: false
					,btn: '我知道了',
					yes:function(){
					        window.location.href='".$url."'
					}
				});
                    </script></body>";
        }
        echo $str;
        exit;

    }

    /**
     * 输出 json
     * @return \think\response\Json
     */
    protected function echo_json($status,$msg ='',$data=''){

        $result['status'] = $status;
        $result['data'] = $data;
        if($msg){
            $result['msg'] = $msg;
        }else{
            $result['msg'] = config('message.public.'.$status);
        }
        return  json($result);
    }

    /**
     * 输出 json
     * @return \think\response\Json
     */
    protected function echo_json_exit($status,$msg ='',$data=''){

        $result['status'] = $status;
        $result['data'] = $data;
        if($msg){
            $result['msg'] = $msg;
        }else{
            $result['msg'] = config('message.public.'.$status);
        }
        echo json_encode($result);
        exit;
    }


    /**
     * 页数
     * @return string
     */
    protected function search_page($type=''){
        if(empty($_GET['page'])){
            $_GET['page']=1;
        }
        $num = 15;
        $page = intval($num * (intval($_GET['page'])?$_GET['page']-1:0));
        if($type=='array'){
            $limit= $page.','.$num;
        }else{
            $limit = " LIMIT $page, $num";
        }
        return $limit;
    }

}
